permalink: /:title
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: sunxboy
  link: http://sunxboy.com
  Twitter: https://twitter.com/sunxboy

# 站点信息
title: 程序之巅
description: 人生如戏，戏如人生
url: http://sunxboy.com
rss_url: /pages/atom.xml
qiniu_url: http://7sbynw.com1.z0.glb.clouddn.com

# gavatar头像及Favicon
gavatar: /public/img/avatar.jpg
favicon: /public/img/favicon.ico

# google analytics 设置
# ga:
#   id: UA-xxxxxxxx-1
#   url: sunxboy.com

# disqus 设置
disqus:
  shortname: sunxboy

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
# cates: 
#   - Python
#   - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
  
exclude: [package.json, gulpfile.js, node_modules, exclude]
